language: node_js
node_js:
  - 16
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run lint
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: clean-react-x
  skip_cleanup: true
notifications:
  email: false
